apiVersion: v1
kind: Namespace
metadata:
  name: <put-namespace-name-here>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: <put-namespace-name-here>
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:      
      containers:
      - name: django
        image: <put-image-name-here>
        imagePullPolicy: Always
        ports:
        - containerPort: <put-container-port-here>
---
apiVersion: v1
kind: Service
metadata:
  name: django-svc
  namespace: <put-namespace-name-here>
spec:
  type: NodePort
  selector:
    app: django
  ports:
  - name: web
    port: 80
    targetPort: <put-container-port-here>  
