kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: django-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: django-pvc
  local:
    path: /tmp
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-172-31-42-9
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: django-sc
  resources:
    requests:
      storage: 1Gi
