apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-pv  
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  
  local:
    path: /tmp
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-172-31-42-9
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-pvc
  namespace: workshop
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
